# Generated by Django 4.1.2 on 2022-10-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackify_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='idol',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
