# Generated by Django 4.1.2 on 2022-10-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackify_app', '0002_alter_project_idol_alter_project_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersetting',
            old_name='clicks',
            new_name='Screenshot_dalay',
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='screenshot',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
