# Generated by Django 4.1 on 2022-10-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackify_app', '0004_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='idol',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
