# Generated by Django 3.1.4 on 2022-10-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackify_app', '0006_auto_20221020_2326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
