# Generated by Django 3.1.4 on 2022-10-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackify_app', '0008_userproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='clicks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='idol',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
