# Generated by Django 3.1.4 on 2022-10-23 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackify_app', '0014_auto_20221021_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheetApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('View', 'View'), ('Submit', 'Submit'), ('Approve', 'Approve'), ('Deny', 'Deny')], default='open', max_length=200, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trackify_app.project')),
            ],
        ),
    ]
