# Generated by Django 3.1.4 on 2022-10-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackify_app', '0015_timesheetapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetapproval',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('View', 'View'), ('Submit', 'Submit'), ('Approve', 'Approve'), ('Deny', 'Deny')], default='Open', max_length=200, null=True),
        ),
    ]
