# Generated by Django 3.1.4 on 2022-10-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackify_app', '0016_auto_20221023_0529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSheetApproval',
            new_name='TimeSheet',
        ),
    ]
